# Generated by Django 5.2.4 on 2025-09-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kundalik', '0003_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='currency',
            field=models.CharField(choices=[('UZS', "So'm"), ('USD', 'Dollar')], default='UZS', max_length=3),
        ),
        migrations.AddField(
            model_name='card',
            name='number',
            field=models.CharField(default=1, max_length=16, unique=True),
            preserve_default=False,
        ),
    ]
