# Generated by Django 5.2.4 on 2025-09-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kundalik', '0005_alter_card_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('kirim', 'Kirim'), ('chiqim', 'Chiqim')], max_length=7),
        ),
    ]
